#include "stdafx.h"
#include "PlaceColonyWithTurrets.h"

/// AUTOGENERATED METHODS ///

int PlaceColonyWithTurrets::AddRef() {
	return Simulator::cStrategy::AddRef();
}
int PlaceColonyWithTurrets::Release() {
	return Simulator::cStrategy::Release();
}

const char* PlaceColonyWithTurrets::GetName() const {
	return "DefaultColony::PlaceColonyWithTurrets";
}

bool PlaceColonyWithTurrets::Write(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Write(stream);
}
bool PlaceColonyWithTurrets::Read(Simulator::ISerializerStream* stream)
{
	return Simulator::ClassSerializer(this, ATTRIBUTES).Read(stream);
}

/// END OF AUTOGENERATED METHODS ///
////////////////////////////////////

Simulator::Attribute PlaceColonyWithTurrets::ATTRIBUTES[] = {
	// Add more attributes here
	// This one must always be at the end
	Simulator::Attribute()
};

void PlaceColonyWithTurrets::Initialize() {
	
}

void PlaceColonyWithTurrets::Dispose() {
	
}

void PlaceColonyWithTurrets::Update(int deltaTime, int deltaGameTime) {
	
}